New Contributor Added
aviyelverse/aviyel-first-pr pull request #76
Opened 2022-08-25 18:34 UTC by TheDeola

2022-08-25 18:38 UTC, siddharth2798 requested changes
Please add description and hyperlink name to the description.

2022-08-25 20:03 UTC, TheDeola commented
Description and hyperlink added. Thanks!

2022-08-26 15:47 UTC, siddharth2798 approved these changes

2022-08-26 15:47 UTC, merged

2022-08-26 15:48 UTC, siddharth2798 commented
Thanks @TheDeola ! You just got rewarded for your contribution!  [Claim it now](https://aviyel.com/projects/54/aviyelverse/rewards)🎉